# Generated by Django 4.1.4 on 2023-01-25 05:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=None, max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNegocio', models.CharField(max_length=500)),
                ('nombreCliente', models.CharField(default=None, max_length=500)),
                ('correo', models.EmailField(default=None, max_length=254)),
                ('logo', models.ImageField(upload_to='logos')),
                ('direccion', models.CharField(default=None, max_length=500)),
                ('ciudad', models.CharField(default=None, max_length=50)),
                ('telefono', models.CharField(default=None, max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tictok', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pais', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.pais')),
            ],
        ),
    ]
