# Generated by Django 4.1.4 on 2022-12-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCodigos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigos',
            name='user',
        ),
    ]
