# Generated by Django 4.1.4 on 2023-01-25 05:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
        ('adminCodigos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idperfil', models.CharField(max_length=500)),
                ('nombreMascota', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombreDueno', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagenPerfil', models.ImageField(blank=True, null=True, upload_to='perfiles')),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('recompensa', models.FloatField(blank=True, max_length=50, null=True)),
                ('esterilizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminCodigos.cliente')),
                ('pais', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.pais')),
            ],
        ),
        migrations.CreateModel(
            name='vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('vacuna', models.CharField(max_length=50)),
                ('dosis', models.CharField(max_length=50)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfilMascotas.perfilmascotas')),
            ],
        ),
        migrations.CreateModel(
            name='peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('peso', models.CharField(max_length=50)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfilMascotas.perfilmascotas')),
            ],
        ),
        migrations.CreateModel(
            name='desparasitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('antiparasitario', models.CharField(max_length=50)),
                ('dosis', models.CharField(max_length=50)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfilMascotas.perfilmascotas')),
            ],
        ),
        migrations.CreateModel(
            name='bano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=300)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfilMascotas.perfilmascotas')),
            ],
        ),
    ]
